// Generated by scripts/import-lyric-sheet.mjs — edit song files, then re-run
// the script (or update imports by hand) when adding songs.
import type { Song } from './types';
import abscond from './songs/abscond';
import bleedYourMind from './songs/bleed-your-mind';
import bloodMoon from './songs/blood-moon';
import drinkGasoline from './songs/drink-gasoline';
import enjoyTheSilence from './songs/enjoy-the-silence';
import goDark from './songs/go-dark';
import imAGhostNow from './songs/im-a-ghost-now';
import seeYouInHell from './songs/see-you-in-hell';
import suchTerribleThings from './songs/such-terrible-things';

export const SONGS: Song[] = [
  abscond,
  bleedYourMind,
  bloodMoon,
  drinkGasoline,
  enjoyTheSilence,
  goDark,
  imAGhostNow,
  seeYouInHell,
  suchTerribleThings,
];

export const songBySlug = (slug: string): Song | undefined =>
  SONGS.find((s) => s.slug === slug);

export * from './types';
export { SETLISTS, DEFAULT_SETLIST_ID } from './setlists';
