import { test, expect } from '@playwright/test';
import { PROTECTED_DOWNLOADS } from './protected';

/**
 * A recruiter clicking "download my resume" and getting a 404 costs exactly as
 * much as a broken page. Both files are generated by scripts (`resume:pdf`,
 * `resume:docx`) and committed into `public/`, so they can silently fall out of
 * the build without anything else noticing.
 */
for (const file of PROTECTED_DOWNLOADS) {
  test(`resume download is intact (${file.path})`, async ({ request, baseURL }) => {
    const response = await request.get(new URL(file.path, baseURL).toString(), {
      failOnStatusCode: false,
    });

    expect(response.status(), `${file.path} did not return 200`).toBe(200);
    expect(response.headers()['content-type'] || '').toMatch(file.type);

    const body = await response.body();
    expect(
      body.byteLength,
      `${file.path} is only ${body.byteLength} bytes — truncated or a placeholder`,
    ).toBeGreaterThan(file.minBytes);
  });
}
